### ISSUE TITLE
error during build using VS Code on windows 7 using cmd

### ISSUE THREAD

**Issue by jameshartling** [purtuga/generator-sharepoint-spa#4]
I am trying to build this great app using VS Code on windows 7 using cmd. Is it possible? I see you say a bash shell is required. here are the errors I get using grunt

C:\x\practice\sp-spa>grunt spa
Loading “Gruntfile.js” tasks…ERROR
>> SyntaxError: Unexpected token &
Warning: Task “spa” not found. Use –force to continue.

Aborted due to warnings.

—————

C:\x\practice\sp-spa>grunt –help
Loading “Gruntfile.js” tasks…ERROR
>> SyntaxError: Unexpected token &
Grunt: The JavaScript Task Runner (v0.4.5)

Usage
grunt [options] [task [task …]]

(followed by the rest of the help output)

Thanks

**Comment by purtuga** [comment]
Hi James.
Thanks for posting here..

I'm not sure this will work with window CMD - never tried it... Do you have [gitbash](https://git-scm.com/downloads) installed? (also: I could be wrong, but I thought VS Code has an embeded CLI? if so, use that since it is likely already a bash type of environment. 

The error above (I think) is saying that the Gruntfile.js can't be parsed... Can you run it with debug mode:

```
grunt -d spa
```
this might output more detailed information as to where the problem is... Also: could you attach your Gruntfile.js file so I can take a look?

I will also try this at a later time using CMD to see if i'm able to pickup on the problem.
